WarsAndConflicts/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WarsAndConflicts.Application.Services;
using WarsAndConflicts.Models;

namespace WarsAndConflicts.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPeriodService _periodService;
        private readonly IWarService _warService;

        public HomeController(ILogger<HomeController> logger, IPeriodService periodService, IWarService warService)
        {
            _logger = logger;
            _periodService = periodService;
            _warService = warService;
        }

        public async Task<ActionResult> Index()
        {
            var periods = await _periodService.GetList();

            return View(periods);
        }

        public async Task<ActionResult> Search(string query)
        {
            var wars = await _warService.Search(query);

            return View(wars);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WarsAndConflicts/Controllers/PeriodController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WarsAndConflicts.Application.Services;
using WarsAndConflicts.DataAccess.Entities;
using WarsAndConflicts.Models;

namespace WarsAndConflicts.Controllers
{
    public class PeriodController : Controller
    {
        private readonly IPeriodService _periodService;
        private readonly IUserService _userService;

        public PeriodController(IPeriodService periodService, IUserService userService)
        {
            _periodService = periodService;
            _userService = userService;
        }

        [HttpGet]
        public async Task<ActionResult> GetPeriod(string id)
        {
            var period = await _periodService.Get(Guid.Parse(id));

            return View(period);
        }

        [HttpGet]
        public ActionResult CreatePeriod()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<ActionResult> CreatePeriod([FromBody] PeriodRequest model)
        {
            var user = await GetUser();

            if(user != null && user.IsAdmin == 1)
            {
                var period = await _periodService.Create(model.Title, model.Description, Convert.FromBase64String(model.Image));

                if(period != null)
                {
                    return StatusCode(200);
                }

                return StatusCode(404);
            }

            return StatusCode(403);
        }

        [HttpPut]
        public async Task<ActionResult> UpdatePeriod(string id, [FromBody] PeriodRequest model)
        {
            var user = await GetUser();

            if (user != null && user.IsAdmin == 1)
            {
                var period = await _periodService.Update(Guid.Parse(id),model.Title, model.Description, Convert.FromBase64String(model.Image));

                if (period != null)
                {
                    return StatusCode(200);
                }

                return StatusCode(404);
            }

            return StatusCode(403);
        }

        [HttpDelete]
        public async Task<ActionResult> RemovePeriod(string id)
        {
            var user = await GetUser();

            if (user != null && user.IsAdmin == 1)
            {
                var isSuccess = await _periodService.Remove(Guid.Parse(id));

                if (isSuccess)
                {
                    return StatusCode(200);
                }

                return StatusCode(404);
            }

            return StatusCode(403);
        }

        private async Task<UserEntity?> GetUser()
        {
            var claimValue = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (claimValue is not null)
            {
                var user = await _userService.Get(Guid.Parse(claimValue));

                return user;
            }

            return null;
        }
    }
}

WarsAndConflicts/Controllers/WarController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WarsAndConflicts.Application.Services;
using WarsAndConflicts.DataAccess.Entities;
using WarsAndConflicts.Models;

namespace WarsAndConflicts.Controllers
{
    public class WarController : Controller
    {
        private readonly IWarService _warService;
        private readonly IUserService _userService;
        private readonly IPeriodService _periodService;

        public WarController(IWarService warService, IUserService userService, IPeriodService periodService)
        {
            _warService = warService;
            _userService = userService;
            _periodService = periodService;
        }

        [HttpGet]
        public async Task<ActionResult> GetWar(string id)
        {
            var war = await _warService.Get(Guid.Parse(id));

            var periods = await _periodService.GetList();

            ViewData["Periods"] = periods;

            return View(war);
        }

        [HttpGet]
        public async Task<ActionResult> CreateWar()
        {
            var periods = await _periodService.GetList();

            return PartialView(periods);
        }

        [HttpPost]
        public async Task<ActionResult> CreateWar([FromBody] WarRequest model)
        {
            var user = await GetUser();

            if (user != null && user.IsAdmin == 1)
            {
                var war = await _warService.Create(model.Title, model.Description, Convert.FromBase64String(model.Image), Guid.Parse(model.PeriodId));

                if (war != null)
                {
                    return StatusCode(200);
                }

                return StatusCode(404);
            }

            return StatusCode(403);
        }

        [HttpPut]
        public async Task<ActionResult> UpdateWar(string id, [FromBody] WarRequest model)
        {
            var user = await GetUser();

            if (user != null && user.IsAdmin == 1)
            {
                var war = await _warService.Update(Guid.Parse(id),model.Title, model.Description, Convert.FromBase64String(model.Image), Guid.Parse(model.PeriodId));

                if (war != null)
                {
                    return StatusCode(200);
                }

                return StatusCode(404);
            }

            return StatusCode(403);
        }

        [HttpDelete]
        public async Task<ActionResult> RemoveWar(string id)
        {
            var user = await GetUser();

            if (user != null && user.IsAdmin == 1)
            {
                var isSuccess = await _warService.Remove(Guid.Parse(id));

                if (isSuccess)
                {
                    return StatusCode(200);
                }

                return StatusCode(404);
            }

            return StatusCode(403);
        }

        private async Task<UserEntity?> GetUser()
        {
            var claimValue = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (claimValue is not null)
            {
                var user = await _userService.Get(Guid.Parse(claimValue));

                return user;
            }

            return null;
        }
    }
}

WarsAndConflicts/Views/Home/Index.cshtml
@model ICollection<WarsAndConflicts.DataAccess.Entities.PeriodEntity>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <h1>Периоды войн и конфликтов</h1>
    <div class="container mt-5">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var period in Model)
            {
                <div class="col">
                    <a href="@Url.Action("GetPeriod", "Period", new { id = period.Id })" class="text-decoration-none">
                        <div class="card">
                            @if (period.Image != null)
                            {
                                var base64Image = Convert.ToBase64String(period.Image);
                                <img src="data:image/jpeg;base64,@base64Image" class="card-img-top" alt="Изображение периода">
                            }
                            else
                            {
                                <img src="https://via.placeholder.com/300x200" class="card-img-top" alt="Изображение периода">
                            }
                            <div class="card-body">
                                <h5 class="card-title text-truncate" title="@period.Title">@period.Title</h5>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

WarsAndConflicts/Views/Home/Search.cshtml
@model ICollection<WarsAndConflicts.DataAccess.Entities.WarEntity>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <h1>Результаты поиска</h1>
    <div class="container mt-5">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var war in Model)
            {
                <div class="col">
                    <a href="@Url.Action("GetWar", "War", new { id = war.Id })" class="text-decoration-none">
                        <div class="card">
                            @if (war.Image != null)
                            {
                                var base64Image = Convert.ToBase64String(war.Image);
                                <img src="data:image/jpeg;base64,@base64Image" class="card-img-top" alt="Изображение войны">
                            }
                            else
                            {
                                <img src="https://via.placeholder.com/300x200" class="card-img-top" alt="Изображение войны">
                            }
                            <div class="card-body">
                                <h5 class="card-title text-truncate" title="@war.Title">@war.Title</h5>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>